palette = 0=#1a1b27
palette = 1=#ff517d
palette = 2=#8cffd1
palette = 3=#ff87d4
palette = 4=#65baff
palette = 5=#fede5d
palette = 6=#78faff
palette = 7=#ffffff
palette = 8=#3c3f58
palette = 9=#ff517d
palette = 10=#8cffd1
palette = 11=#ff87d4
palette = 12=#65baff
palette = 13=#ffd36e
palette = 14=#78faff
palette = 15=#ffffff
background = #2a2139
foreground = #e2e8ff
selection-background = #f9c5d1
selection-foreground = #2a2139
cursor-color = #ff70a6
cursor-text = #2a2139
