[unlam-dev]
# Usamos la imagen oficial de Arch para que los comandos sean iguales
image=archlinux:latest

# Si ya existe, lo reemplaza (útil para actualizar la "receta")
replace=true

# Paquetes esenciales para la facultad, compilación y gráficos
packages="base-devel codeblocks clang gdb git glibc-locales mesa vulkan-radeon nvim zsh zoxide eza zip unzip wget sudo"

# Esto permite que las apps gráficas (CodeBlocks) se vean en Hyprland
init=false
nvidia=false
pull=true

# Script para que al crearse ya tenga PARU instalado (opcional pero recomendado)
additional_packages="git base-devel"
pre_init_hooks="if ! command -v paru &> /dev/null; then git clone https://aur.archlinux.org/paru-bin.git /tmp/paru-bin && cd /tmp/paru-bin && makepkg -si --noconfirm; fi"
