palette = 0=#151720
palette = 1=#dd6777
palette = 2=#86aaec
palette = 3=#ecd3a0
palette = 4=#90ceaa
palette = 5=#c296eb
palette = 6=#93cee9
palette = 7=#cbced3
palette = 8=#1c1e27
palette = 9=#e26c7c
palette = 10=#8baff1
palette = 11=#f1d8a5
palette = 12=#95d3af
palette = 13=#c79bf0
palette = 14=#98d3ee
palette = 15=#d0d3d8
background = #0d0f18
foreground = #a5b6cf
selection-background = #1c1e27
selection-foreground = #a5b6cf
cursor-color = #cbced3
cursor-text = #a5b6cf
